//! Demo crate showing how a versioned Serde schema can be laid out for `berde` migrations.
//!
//! Each schema version lives in its own module under `src/versions/` (e.g. `v1.rs`, `v2.rs`),
//! and the crate's build script generates:
//!
//! - the module declarations for [`versions`] from those files, and
//! - a [`latest`] alias at the crate root for the highest-numbered version module.

/// One submodule per schema version (`v1`, `v2`, ...).
///
/// The contents of this module are generated at build time by `build.rs`, which scans
/// `src/versions/` for files named `vN.rs`, sorts them numerically by `N`, and declares each as
/// `pub mod vN`. Each submodule defines a `Schema` type representing that version's data layout.
pub mod versions {
    include!(concat!(env!("OUT_DIR"), "/versions.rs"));
}

// Alias for the highest-numbered module in `versions`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/latest.rs"));
