//! Crate root for `berde`.
//!
//! This crate is in early scaffolding and currently contains only the placeholder code
//! generated by `cargo new`. It will be replaced as the Serde data file migration system is
//! implemented.

/// Adds two values together.
///
/// # Parameters
/// - `left`: the first operand.
/// - `right`: the second operand.
///
/// # Returns
/// The sum of `left` and `right`.
pub fn add(left: u64, right: u64) -> u64 {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
